CREATE TABLE IF NOT EXISTS Genre (
	Genre_ID SERIAL PRIMARY KEY,
	Name VARCHAR(80) NOT NULL
);

CREATE TABLE IF NOT EXISTS Artists (
	Artist_ID SERIAL PRIMARY KEY,
	Name VARCHAR(80)
);

CREATE TABLE IF NOT EXISTS ArtistsGenre (
	Artist_ID INTEGER REFERENCES Artists(Artist_ID),
	Genre_ID INTEGER REFERENCES Genre(Genre_ID),
	CONSTRAINT pf PRIMARY KEY(Artist_ID, Genre_ID)
);

CREATE TABLE IF NOT EXISTS Albums (
	Album_ID SERIAL PRIMARY KEY,
	Name VARCHAR(80) NOT NULL,
	Release_Date DATE
);

CREATE TABLE IF NOT EXISTS ArtistsAlbums (
	Artist_ID INTEGER REFERENCES Artists(Artist_ID),
	Album_ID INTEGER REFERENCES Albums(Album_ID),
	CONSTRAINT pk_aa PRIMARY KEY(Artist_ID, Album_ID)
);

CREATE TABLE IF NOT EXISTS Tracks (
	Track_ID SERIAL PRIMARY KEY, 
	Name VARCHAR(80) NOT NULL,
	Duration INTEGER NOT NULL,
	Album_ID INTEGER NOT NULL REFERENCES Albums(Album_ID)
);

CREATE TABLE IF NOT EXISTS Collections (
	Collection_ID SERIAL PRIMARY KEY,
	Name VARCHAR(80),
	Realease_Date DATE
);

CREATE TABLE IF NOT EXISTS ColectionsTracks (
	Collection_ID INTEGER REFERENCES Collections(Collection_ID),
	Track_ID INTEGER REFERENCES Tracks(TRACK_ID),
	CONSTRAINT pk_ct PRIMARY KEY(Collection_ID, Track_ID)
);
